feat: support for reading from Immutable DB
blinklabs-io/node pull request #13
Opened 2024-04-26 19:33 UTC by agaffney

Fixes #12

2024-04-27 21:32 UTC, wolf31o2 requested changes

2024-04-27 21:32 UTC, wolf31o2 commented on database/immutable/chunk.go
> +	if c.nextEntry == nil {
When would this occur? Byron? Add a comment.

2024-04-27 21:32 UTC, wolf31o2 commented on database/immutable/immutable.go
> +			// We found the chunk that (probably) has the requested point
:sweat_smile:

2024-04-28 21:36 UTC, agaffney commented on database/immutable/chunk.go
> +	if c.nextEntry == nil {
Comments added

2024-04-28 21:38 UTC, wolf31o2 approved these changes

2024-04-28 23:00 UTC, merged